; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:teensy41]
platform = teensy
board = teensy41
framework = arduino
build_type = release
build_unflags = -fexceptions
build_flags = 
	-DFWVERSION=0.6
    -fno-exceptions
	-DPlatformTeensy
    -DWD_EXPIRE=2 ; 2 sec
    -DENABLE_WD ; DISABLE_WD for the debug
	-DLOGGER_SIZE=256
	-DLoggerSerialDev=Serial7
	-DSERIAL_BAUDRATE=256000
	-D_TASK_STD_FUNCTION
	-D_TASK_MICRO_RES
	-DUSB_DUAL_SERIAL
	-DCmdSerialDev=Serial1
	-DWATCHDOG_LED=13
	-DOSDP_PORT_PULL_RATE=100 ; 100 uSec
	-DOSDP_PORT_BAUD_RATE=9600
	-DSerialReader1_232Port=Serial
	-DSerialReader2_232Port=SerialUSB1
	-DSTEPPER_STEP_TIME_USEC=6600
	-DSTEPPER_SLEEP_TIMEOUT_USEC=120000000
	-DOSDP_PULL_RATE_USEC=100
	-DWIEGAND_MAX_BITS=256
	-DINTER_WIEGAND_BITS_TIMEOUT_MSEC=25
	-DPROMT=\"bdtf$\ \"
	

monitor_speed = 115200
; monitor_port = disable
lib_deps = 
	arkhipenko/TaskScheduler
	bblanchon/ArduinoJson @ ^7.4.3
	https://github.com/FrankBoesing/FastCRC.git#c669a89
	https://github.com/SMFSW/Queue#6bd9a4e
	https://github.com/tonton81/WDT_T4#1910b57
	https://github.com/jnk0le/Ring-Buffer.git#160190e
	https://github.com/lbuchman/CmdArduino.git
	https://github.com/lbuchman/loggingLib.git
	https://github.com/lbuchman/SimpleEvents.git#37aef6a
